### ISSUE TITLE
Remove hard-coded observation uncertainties

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/flownet#120]
Observation uncertainties are currently hard-coded:
https://github.com/equinor/flownet/blob/038256cd87e4c598ae8ac2167c8899774df6f6e4/src/flownet/templates/observations.ertobs.jinja2#L11-L42
https://github.com/equinor/flownet/blob/038256cd87e4c598ae8ac2167c8899774df6f6e4/src/flownet/templates/observations.yamlobs.jinja2#L10-L73

The user should have ownership to these (at least as long as observations and uncertainties are not extracted automatically from raw data in some future). Maybe the currently hard-coded values (both % and min. absolute value) should be moved to config, with no default value?

**Comment by wouterjdb** [comment]
Suggestion from stand-up:
```
name: Norne

flownet:
  data_source:
    simulation:
      input_case: ../tests/data/norne/NORNE_ATW2013
      vectors:
        WTHP:            
          min_error: 10
          rel_error: 50%
        WBHP:
          abs: 10
          rel: 50%
        FOPR:
         
          
  phases:
    - oil
    - gas
    - vapoil
    - disgas
    - water
  pvt:
```
