### ISSUE TITLE
Handling overlapping GOC / WOC ranges

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#165]
The `EQUIL` keyword in Norne looks like:

![image](https://user-images.githubusercontent.com/9119793/92088878-c0fb6180-edcd-11ea-8e12-01091a751670.png)

In FlowNet we currently only allow a single range for OWC depth, and a single range for GOC depth. This makes it impossible to model region 4, which has very shallow contacts, at the same time as the other regions as the ranges for GOC and WOC would be overlapping. Simulations where GOC would depper than OWC would fail.

For the `individual` scheme it might be hard to supply individual ranges, but one could potentially apply limits to either one of the contacts based on the sample of the other contact. This would however violated assumptions on independence in the ensemble smoother. Not entirely decoupled, but maybe only setting one of the two and the thickness of the oil bearing zone could be anther option?

**However,** for the newly created 'regions_from_sim' , #160, it _is_ feasible to require the user to supply a range of OWC/GOC for each region.

What do you think @olelod?

**Comment by wouterjdb** [comment]
Could this be a potential implementation:


```yaml
model_parameters:
  equil:
    scheme: regions_from_sim
    datum_pressure:
      min: 250
      max: 275
    owc_depth:
      min: 2675
      max: 2725
    goc_depth:
      min: 2575
      max: 2600
    region:
      id: 1
        datum_pressure:
          min: 250
          max: 275
        owc_depth:
          min: 1234
          max: 5678
        goc_depth:
          min: 100
          max: 1000
    region:
      id: 5
        datum_pressure:
          min: 250
          max: 275
        owc_depth:
          min: 9999
          max: 8888
        goc_depth:
          min: 6666
          max: 7777
```

Where two regions (EQLNUMs) have an override from the default. If no override is given the default is used.
