### ISSUE TITLE
Incorrect usage of lists in yaml in the analytics configuration

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#241]
Incorrect usage of list in in YAML file for analysis configiration:

```
  analysis:
    metric: "[RMSE,MAE]"
    quantity: "[WOPR:PROD,WWPR:PROD]"
    start: "2011-01-01"
    end: "2016-06-01"
    outfile: analysis_metrics_iteration
```
