### ISSUE TITLE
Add option for setting a constant value for a parameter

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/flownet#32]
Original author: @wouterjdb 

We're adding more and more parameters increasing the degrees of freedom. For some parameters it would maybe not always make sense to add them as an uncertain parameter, but a constant might be good enough. This is currently not supported.

I suggest that something like this would be allowed in the config:

```yaml
model_parameters:
  permeability:
    min: 0.1
    max: 2000
  bulkvolume_mult:
    constant: 1
```

**Comment by wouterjdb** [comment]
@olelod is this already supported?

**Comment by olelod** [comment]
Yes, it should be. Like this:

```
model_parameters:
  permeability:
    min: 0.1
    max: 2000
  bulkvolume_mult:
    base: 1
    distribution: const
```
