### ISSUE TITLE
Check initial pressure in the Norne model

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#375]
Ref discussion here: https://github.com/equinor/flownet/pull/372

Check that we use the correct initial pressure in all regions.

**Comment by edubarrosTNO** [comment]
I have checked this today: there is an inconsistency between the equilibration settings of region 4 in the config file and in the EQUIL keyword of the reference Norne simulation.
https://github.com/equinor/flownet-testdata/blob/48e4273b04ee33c2643e6d07acf9291fd50caf8f/norne/config/assisted_history_matching.yml#L187-L191
```
      - id: 4
        datum_depth: 2200
        datum_pressure:
          min: 260
          max: 280
```

```
EQUIL
   (...)
   2200.0  236.92  2400.00  0.0  2200.00  0.0  4  0  0  /  G: Ile-Tilje
   (...)
```

**Comment by edubarrosTNO** [comment]
I will fix it in a PR tomorrow, with:
```
      - id: 4
        datum_depth: 2200
        datum_pressure:
          min: 230
          max: 250
```
