### ISSUE TITLE
Support for BRINE

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#381]
Implement support for `BRINE`
====================
Allows a FlowNet to be able to history match total dissolved salts (TDS) in  produced water.

Suggested way of working
-----------------------------
The usage of the brine model, or brine historic data import should all behave as **optional** ❗ 

- [x] 1) Add dummy salt data to the Norne model such that we can extract the salt observations from the simulation file. (this ommits the need for #382)

    Minimum required salt-related keywords for single component model:
    `BRINE`
    `PVTWSALT`
    `WSALT`
    `SALTVD`

    See the [OPM Flow Manuel](https://opm-project.org/wp-content/uploads/2020/12/OPM_Flow_Documentation_2020-10_Rev-0.pdf) for details on keywords that need to be supported.

- [x] 2) Add support for the `WSPR` (Well Salt Production Rate) and `WSIR` (Well Salt Injection Rate) summary vectors in https://github.com/equinor/flownet/blob/de23dc0c8d9f6f8841167ece40ea070d4834c00e/src/flownet/data/from_flow.py#L152

- [x] 3) Add support for `WSPR` to as observation vector in a YAML configuration, like so:

    ```yaml
    name: Norne
    
    flownet:
      data_source:
        simulation:
          input_case: ../input_model/norne/NORNE_ATW2013
          vectors:
            WBHP:
              rel_error: 0.05
              min_error: 10
            WOPR:
              rel_error: 0.1
              min_error: 100
            WGPR:
              rel_error: 0.1
              min_error: 100000
            WSPR:
              rel_error: 0.2
              min_error: 10
    ```
    ie, update the config parser https://github.com/equinor/flownet/blob/master/src/flownet/config_parser/_config_parser.py.

- [x] 4) Add `WSPR` to the observations.ertobs and yaml obs template:
https://github.com/equinor/flownet/blob/master/src/flownet/templates/observations.ertobs.jinja2
https://github.com/equinor/flownet/blob/master/src/flownet/templates/observations.yamlobs.jinja2
and update the https://github.com/equinor/flownet/blob/master/tests/test_check_obsfiles_ert_yaml.py file.

- [x] 5) Add `WSPR` and `WSIR`, when used, to the https://github.com/equinor/flownet/blob/master/src/flownet/static/SUMMARY.inc file.

- [ ] 6) Add `WSPR` and `WSIR` support to the schedule creation, https://github.com/equinor/flownet/blob/master/src/flownet/realization/_schedule.py. Also add to schedule template.

- [ ] 7) Update the FlowNet Flow model template to include the Brine model (as was done for the Norne model in _step 1_).
